- name: Tp7
  hosts: main
  remote_user: ambient-user
  become: true
  become_user: root
  vars:
    csvfile: "/home/ambient-user/advanced_ansible_course/tp7/temperature.csv"
    local_longitude: "7.00649100"
    local_latitude: "43.60233190"

  tasks:
    - name: Read Csv
      community.general.read_csv:
        path: "{{ csvfile }}"
        delimiter: ','
      register: csvdata

    - name: Clean + sort
      ansible.builtin.set_fact:
        dataok: "{{ csvdata.list | unique | sort(attribute='time') }}"

    - name: Display
      ansible.builtin.debug:
        var: dataok

    - name: Facts
      ansible.builtin.set_fact:
        urlapimougins: "https://api.open-meteo.com/v1/forecast?latitude={{ local_latitude }}&longitude={{ local_longitude }}&current=temperature_2m"
        urlapicompare: "https://api.open-meteo.com/v1/forecast?latitude=48.86&longitude=2.33&current=temperature_2m"

    - name: Call api Mougins
      ansible.builtin.uri:
        url: "{{ urlapimougins }}"
        method: GET
        return_content: true
      register: apiresmougins

    - name: Call api Compare
      ansible.builtin.uri:
        url: "{{ urlapicompare }}"
        method: GET
        return_content: true
      register: apirescompare

    - name: Display current temp Mougins
      ansible.builtin.debug:
        var: apiresmougins.json.current.temperature_2m

    - name: Display  current temp Compare
      ansible.builtin.debug:
        var: apirescompare.json.current.temperature_2m

    - name: Facts compare
      ansible.builtin.set_fact:
        plusfroid: "{{ apirescompare.json.current.temperature_2m | float > apiresmougins.json.current.temperature_2m | float }}"
        pluschaud: "{{ apirescompare.json.current.temperature_2m | float < apiresmougins.json.current.temperature_2m | float }}"
        pareil: "{{ apirescompare.json.current.temperature_2m | float == apiresmougins.json.current.temperature_2m | float }}"

    - name: Display
      ansible.builtin.debug:
        msg: "plusfroid={{ plusfroid }} /pluschaud={{ pluschaud }} /pareil={{ pareil }} / "

    - name: Comparaison froid
      ansible.builtin.debug:
        msg: "Il fait plus froid a Mougins "
      when: plusfroid

    - name: Comparaison chaud
      ansible.builtin.debug:
        msg: "Il fait plus chaud a Mougins "
      when: pluschaud

    - name: Comparaison pareil
      ansible.builtin.debug:
        msg: "Il fait la meme temp "
      when: pareil

    - name: Reverse
      ansible.builtin.debug:
        msg: "{{ item | reverse }}"
      with_items:
        -{{ apiresmougins.json.current.temperature_2m }} 
        -{{ apirescompare.json.current.temperature_2m }} 