- name: Install softwares machine1
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apache2
    - mysql-server
  when: ansible_facts['nodename'] == "node01" or ansible_facts['nodename'] == "node02"

- name: Install softwares machine3
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - git
    - nginx
    - cowsay
  when: ansible_facts['nodename'] == "node03"

- name: Install pecific ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - ufw
  when: ansible_distribution == "Ubuntu"


- name: Check {{ html_root }}
  ansible.builtin.file:
    path: "{{ html_root }}"
    state: directory
    mode: '0644'

- name: Delete index.html
  ansible.builtin.file:
    path: "{{ html_root }}/index.html"
    state: absent


- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Write content html
  ansible.builtin.lineinfile:
    path: "{{ html_root }}/index.html"
    line: "<h1>Bonjour depuis Ansible sur {{ ansible_hostname }}  {{ ansible_date_time.date }}</h1>"
    mode: '0644'
    create: true
  when: "'apache2' in ansible_facts.packages or 'nginx' in ansible_facts.packages"

- name: Gestion service apache
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_facts['nodename'] == "node01" or ansible_facts['nodename'] == "node02"

- name: Gestion service nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  when: ansible_facts['nodename'] == "node03"

- name: Creation jour
  ansible.builtin.template:
    src: templates/jour.ini.j2
    dest: "{{ etcjour }}"
    mode: '0644'
  tags: test

- name: Write jour pair>12h
  ansible.builtin.lineinfile:
    path: "{{ etcjour }}"
    line: "pair et plus tard que midi"
    mode: '0644'
    create: true
  when: (ansible_facts['date_time']['hour']|int > 12) and (ansible_facts['date_time']['day']|int % 2 == 0)


- name: Write jour pair<=12h
  ansible.builtin.lineinfile:
    path: "{{ etcjour }}"
    line: "pair et avant que midi"
    mode: '0644'
    create: true
  when: (ansible_facts['date_time']['hour']|int <= 12) and (ansible_facts['date_time']['day']|int % 2 == 0)

- name: Write jour impair>12h
  ansible.builtin.lineinfile:
    path: "{{ etcjour }}"
    line: "impair et plus tard que midi"
    mode: '0644'
    create: true
  when: (ansible_facts['date_time']['hour']|int > 12) and (ansible_facts['date_time']['day']|int % 2 == 1)


- name: Write jour impair<=12h
  ansible.builtin.lineinfile:
    path: "{{ etcjour }}"
    line: "impair et avant que midi"
    mode: '0644'
    create: true
  when: (ansible_facts['date_time']['hour']|int <= 12) and (ansible_facts['date_time']['day']|int % 2  == 1)
