[all]
10.0.0.55 ansible_become_password='ambient'
10.0.0.56 ansible_become_password='ambient'
10.0.0.57 ansible_become_password='ambient'

[web]
10.0.0.56 ansible_become_password='ambient'

[db]
10.0.0.57 ansible_become_password='ambient'
