- name: Tp6
  hosts: all
  remote_user: ambient-user
  become: true
  become_user: root
  vars_files:
    - vars/db.yaml
    - vars/web.yaml
    - vault.yaml

  tasks:

    - name: Install wordpress on node2
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apache2
        - wordpress
        - ghostscript
        - libapache2-mod-php
        - php
        - php-bcmath
        - php-curl
        - php-imagick
        - php-intl
        - php-json
        - php-mbstring
        - php-mysql
        - php-xml
        - php-zip
      when: ansible_facts['nodename'] == "node02"
      tags: install

    - name: Install myslq-server on node3
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - mysql-server
      when: ansible_facts['nodename'] == "node03"
      tags: install

    - name: Debug
      ansible.builtin.debug:
        msg:
        - "mysql_user_name {{ mysql_user_name }}" 
        - "ansible_default_ipv4.address {{ ansible_default_ipv4.address }}" 
        - "mysql_databases[0].name {{ mysql_databases[0].name }}"
        - "salut {{ salut }}"
      tags: fact

    - name: Install mysql-server
      ansible.builtin.include_role:
        name: geerlingguy.mysql
      tags: ok
      when: ansible_facts['nodename'] == "node03"

    - name: Generation conf apache
      ansible.builtin.template:
        src: templates/wp-config.ini.j2
        dest: "/usr/share/wordpress/wp-config.php"
      tags: test


    - name: Generation conf 
      ansible.builtin.template:
        src: templates/wordpress.conf.ini
        dest: "/etc/apache2/sites-available/wordpress.conf"
      tags: test
